modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="gamer"
version="1.0.0"
displayName="gamer"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="pölli forestlord, MCreator"

[[dependencies.gamer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




